{% set version = "4.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sparkr
  version: {{ version }}

source:
  url: https://dist.apache.org/repos/dist/release/spark/spark-{{ version }}/SparkR_{{ version }}.tar.gz
  sha256: 4480c4904dd7771676285e0049e24fce7b3a95baa35007cb30fbadc02800e538

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('SparkR')"           # [not win]
    - "\"%R%\" -e \"library('SparkR')\""  # [win]

about:
  home: http://spark.apache.org/
  dev_url: https://github.com/apache/spark
  license: Apache-2.0
  license_file: LICENSE
  summary: Provides an R Front end for 'Apache Spark' <https://spark.apache.org>.

extra:
  recipe-maintainers:
    - zero323
    - conda-forge/r
